// This file should be generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id your_project_id > types/supabase.ts

export type Database = {
  public: {
    Tables: {
      // Define your tables here
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};
